/** Source-parity copy for the owner-authorized six-template pilot.
 * Copy is derived from the read-only backend locale YAMLs; payloads are synthetic.
 */
export const PILOT_SAMPLE = {
  resetCode: '482 913',
  reviewNote: 'Please clarify the venue accessibility plan and upload the updated permit.',
  refund: {
    paymentMethod: 'Credit card',
    items: [
      { id: 'TKT-18402', name: 'General Admission', type: 'Ticket', quantity: '2', cost: 'CA$80.00', fees: 'CA$2.50', tax: 'CA$10.40', total: 'CA$92.90' },
    ],
    canceled: [{ id: 'ADD-204', name: 'Festival guide', type: 'Add-on', quantity: '1' }],
  },
  contact: {
    business: 'Northwind Events',
    topic: 'Partnership inquiry',
    message: 'We would like to discuss ticketing for a three-day community event. Please contact us next week.',
  },
  announcement: {
    subject: 'Important event entrance update',
    body: 'The east entrance will open at 5:30 PM. Please bring your ticket and use the entrance shown on the event map.',
  },
};

export const PILOT_LOCALES = {
  en: {
    password: { title:'Eveenty Password Reset', heading:'Password Reset Request', hello:'Hello', body:'We received a request to reset the password for your Eveenty account. To proceed, please use the verification code below in the Eveenty app:', ignoreBefore:'If you did not request this password reset, please ignore this email or ', ignoreLink:'contact our support team', ignoreAfter:' immediately.', sentTo:'This message was sent to', copyright:'© Eveenty, 10 - 225 The East Mall Suite #1264 - Toronto - ON - M9B 0A9' },
    refund: { title:'Refund receipt', headline:'{{user}} purchases from {{festival}} have been refunded', name:'Client name', address:'Client address', phone:'Client phone', email:'Client email', date:'Date', payment:'Payment method', creditCard:'Credit card', refunded:'Refunded items', success:'The following items have been successfully refunded. You should expect the money to show on your account within 3–5 business days.', canceled:'Canceled items', canceledIntro:'The following items have been canceled. Since these items were free, no refund was issued. However, they are no longer valid.', id:'ID', item:'Name', type:'Type', qty:'Quantity', cost:'Cost', fees:'Processing fees', tax:'Tax', total:'Total', amount:'Amount', bank:'Bank fees', totalRefunded:'Total refunded' },
    reject: { user:'We regret to inform you that your ticket registration for {{festival}} was not approved at this time. If you have questions, please contact the event organizer.', organizer:'Hi {{name}} 👋, a ticket registration for your event has been rejected.', admin:'Hi Eveenty 👋, a ticket registration has been rejected.', alert:'This ticket registration has been rejected.', status:'Rejected', registrationId:'Registration ID', registrationDate:'Registration Date & Time', currentStatus:'Current Status', reviewDeadline:'Review Deadline', name:'Name', email:'Email', phone:'Phone', ticketType:'Ticket Type', ticketHolder:'Ticket Holder' },
    approval: { title:'Festival review update', approvedTitle:'Festival approved', rejectedTitle:'Festival not approved', greeting:'Dear {{name}},', approved:'We are thrilled to inform you that your festival, {{festival}}, has been successfully approved! After a thorough review, we have ensured that all the necessary criteria have been met, and your event is now ready to be published. You can now share your festival with the world and attract attendees. If you have any further details to update or need assistance, our team is here to support you. Congratulations on your successful submission, and we look forward to seeing your festival come to life!', rejected:'Thank you for submitting your festival, {{festival}}, for review. After careful consideration, we regret to inform you that your festival has not been approved at this time. While we appreciate your effort and creativity, there are certain criteria that need to be met before the festival can be published. Our team is here to assist you with any questions or guidance you may need.', notes:'Review notes', notesIntro:'Here you can find useful information about the review process:' },
  },
  fr: {
    password: { title:'Réinitialisation du mot de passe Eveenty', heading:'Demande de réinitialisation du mot de passe', hello:'Bonjour', body:"Nous avons reçu une demande de réinitialisation du mot de passe pour votre compte Eveenty. Pour continuer, veuillez utiliser le code de vérification ci-dessous dans l'application Eveenty :", ignoreBefore:"Si vous n'avez pas demandé cette réinitialisation, veuillez ignorer cet e-mail ou ", ignoreLink:"contacter notre équipe d'assistance", ignoreAfter:' immédiatement.', sentTo:'Ce message a été envoyé à', copyright:'© Eveenty, 10 - 225 The East Mall Suite #1264 - Toronto - ON - M9B 0A9' },
    refund: { title:'Reçu de remboursement', headline:'Les achats de {{user}} pour {{festival}} ont été remboursés', name:'Nom du client', address:'Adresse du client', phone:'Téléphone du client', email:'Courriel du client', date:'Date', payment:'Mode de paiement', creditCard:'Carte de crédit', refunded:'Articles remboursés', success:'Les articles suivants ont été remboursés avec succès. Le montant devrait apparaître sur votre compte sous 3 à 5 jours ouvrables.', canceled:'Articles annulés', canceledIntro:"Les articles suivants ont été annulés. Comme ils étaient gratuits, aucun remboursement n'a été émis, mais ils ne sont plus valides.", id:'ID', item:'Nom', type:'Type', qty:'Quantité', cost:'Coût', fees:'Frais de traitement', tax:'Taxe', total:'Total', amount:'Montant', bank:'Frais bancaires', totalRefunded:'Total remboursé' },
    reject: { user:"Nous regrettons de vous informer que votre inscription pour l'événement {{festival}} n'a pas été approuvée. Pour toute question, veuillez contacter l'organisateur de l'événement.", organizer:'Bonjour {{name}} 👋, une inscription de billet pour votre événement a été rejetée.', admin:'Bonjour Eveenty 👋, une inscription de billet a été rejetée.', alert:'Cette inscription de billets a été refusée.', status:'Refusé', registrationId:"N° d'inscription", registrationDate:"Date et heure d'inscription", currentStatus:'Statut actuel', reviewDeadline:'Date limite de révision', name:'Nom', email:'E-mail', phone:'Téléphone', ticketType:'Type de billet', ticketHolder:'Titulaire du billet' },
    approval: { title:'Mise à jour de l’examen du festival', approvedTitle:'Festival approuvé', rejectedTitle:'Festival non approuvé', greeting:'Bonjour {{name}},', approved:'Nous avons le plaisir de vous informer que votre festival, {{festival}}, a été approuvé avec succès ! Après un examen approfondi, nous avons vérifié que tous les critères nécessaires sont remplis et que votre événement peut désormais être publié. Vous pouvez maintenant partager votre festival et attirer des participants. Si vous devez mettre à jour des informations ou avez besoin d’aide, notre équipe est là pour vous accompagner. Félicitations pour votre soumission, et nous avons hâte de voir votre festival prendre vie !', rejected:'Merci d’avoir soumis votre festival, {{festival}}, pour examen. Après mûre réflexion, nous regrettons de vous informer que votre festival n’a pas été approuvé pour le moment. Nous apprécions vos efforts et votre créativité ; certains critères doivent encore être satisfaits avant publication. Notre équipe peut répondre à vos questions et vous orienter si besoin.', notes:'Notes d’examen', notesIntro:'Vous trouverez ici des informations utiles sur le processus d’examen :' },
  },
  es: {
    password: { title:'Restablecimiento de contraseña de Eveenty', heading:'Solicitud de restablecimiento de contraseña', hello:'Hola', body:'Hemos recibido una solicitud para restablecer la contraseña de su cuenta Eveenty. Para continuar, utilice el código de verificación que aparece a continuación en la aplicación Eveenty:', ignoreBefore:'Si no solicitó este restablecimiento de contraseña, ignore este correo o ', ignoreLink:'contacte a nuestro equipo de soporte', ignoreAfter:' de inmediato.', sentTo:'Este mensaje se envió a', copyright:'© Eveenty, 10 - 225 The East Mall Suite #1264 - Toronto - ON - M9B 0A9' },
    refund: { title:'Recibo de reembolso', headline:'Las compras de {{user}} en {{festival}} han sido reembolsadas', name:'Nombre del cliente', address:'Dirección del cliente', phone:'Teléfono del cliente', email:'Correo del cliente', date:'Fecha', payment:'Método de pago', creditCard:'Tarjeta de crédito', refunded:'Artículos reembolsados', success:'Los siguientes artículos se han reembolsado correctamente. El importe debería aparecer en su cuenta en 3 a 5 días hábiles.', canceled:'Artículos cancelados', canceledIntro:'Se han cancelado los siguientes artículos. Al ser gratuitos, no se ha emitido reembolso, pero ya no son válidos.', id:'ID', item:'Nombre', type:'Tipo', qty:'Cantidad', cost:'Coste', fees:'Comisiones de procesamiento', tax:'Impuesto', total:'Total', amount:'Importe', bank:'Comisiones bancarias', totalRefunded:'Total reembolsado' },
    reject: { user:'Lamentamos informarte que tu inscripción para el evento {{festival}} no fue aprobada en este momento. Si tienes preguntas, por favor contacta al organizador del evento.', organizer:'Hola {{name}} 👋, una inscripción de entrada para tu evento ha sido rechazada.', admin:'Hola Eveenty 👋, una inscripción de entrada ha sido rechazada.', alert:'Esta inscripción de entradas ha sido rechazada.', status:'Rechazado', registrationId:'N.º de inscripción', registrationDate:'Fecha y hora de inscripción', currentStatus:'Estado actual', reviewDeadline:'Fecha límite de revisión', name:'Nombre', email:'Correo electrónico', phone:'Teléfono', ticketType:'Tipo de entrada', ticketHolder:'Titular de la entrada' },
    approval: { title:'Actualización de la revisión del festival', approvedTitle:'Festival aprobado', rejectedTitle:'Festival no aprobado', greeting:'Estimado/a {{name}},', approved:'Nos complace informarte de que tu festival, {{festival}}, ¡ha sido aprobado con éxito! Tras una revisión exhaustiva, hemos comprobado que se cumplen todos los criterios necesarios y que tu evento ya puede publicarse. Ya puedes compartir tu festival con el mundo y atraer asistentes. Si necesitas actualizar algún detalle o ayuda, nuestro equipo está aquí para apoyarte. ¡Enhorabuena por tu envío, y esperamos ver tu festival en marcha!', rejected:'Gracias por enviar tu festival, {{festival}}, para su revisión. Tras considerarlo con detenimiento, lamentamos informarte de que tu festival no ha sido aprobado en este momento. Apreciamos tu esfuerzo y creatividad; es necesario cumplir ciertos criterios antes de que el festival pueda publicarse. Nuestro equipo puede ayudarte con cualquier duda u orientación que necesites.', notes:'Notas de la revisión', notesIntro:'Aquí encontrarás información útil sobre el proceso de revisión:' },
  },
  ar: {
    password: { title:'إعادة تعيين كلمة مرور ايفينتي', heading:'طلب إعادة تعيين كلمة المرور', hello:'مرحباً', body:'تلقينا طلباً لإعادة تعيين كلمة مرور حساب ايفينتي الخاص بك. للمتابعة، يرجى استخدام رمز التحقق أدناه في تطبيق ايفينتي:', ignoreBefore:'إذا لم تطلب إعادة تعيين كلمة المرور، يُرجى تجاهل هذا البريد أو ', ignoreLink:'التواصل مع فريق الدعم', ignoreAfter:' على الفور.', sentTo:'تم إرسال هذه الرسالة إلى', copyright:'© Eveenty، 10 - 225 The East Mall Suite #1264 - تورونتو - أونتاريو - M9B 0A9' },
    refund: { title:'إيصال استرداد', headline:'تم استرداد مشتريات {{user}} من {{festival}}', name:'اسم العميل', address:'عنوان العميل', phone:'هاتف العميل', email:'البريد الإلكتروني للعميل', date:'التاريخ', payment:'طريقة الدفع', creditCard:'بطاقة ائتمان', refunded:'العناصر المستردة', success:'تم استرداد العناصر التالية بنجاح. يُتوقع ظهور المبلغ في حسابك خلال 3 إلى 5 أيام عمل.', canceled:'عناصر ملغاة', canceledIntro:'تم إلغاء العناصر التالية. وبما أنها كانت مجانية، لم يُصدر استرداد. لكنها لم تعد صالحة.', id:'المعرّف', item:'الاسم', type:'النوع', qty:'الكمية', cost:'التكلفة', fees:'رسوم المعالجة', tax:'الضريبة', total:'الإجمالي', amount:'المبلغ', bank:'رسوم البنك', totalRefunded:'إجمالي المسترد' },
    reject: { user:'نأسف لإبلاغك بأن تسجيلك في فعالية {{festival}} لم يتم قبوله في هذا الوقت. إذا كانت لديك أسئلة، يرجى التواصل مع منظم الفعالية.', organizer:'مرحباً {{name}} 👋، تم رفض تسجيل تذكرة لفعاليتك.', admin:'مرحباً Eveenty 👋، تم رفض تسجيل تذكرة.', alert:'تم رفض طلب تسجيل التذاكر هذا.', status:'مرفوض', registrationId:'رقم التسجيل', registrationDate:'تاريخ ووقت التسجيل', currentStatus:'الحالة الحالية', reviewDeadline:'موعد انتهاء المراجعة', name:'الاسم', email:'البريد الإلكتروني', phone:'رقم الهاتف', ticketType:'نوع التذكرة', ticketHolder:'حامل التذكرة' },
    approval: { title:'تحديث مراجعة المهرجان', approvedTitle:'تمت الموافقة على المهرجان', rejectedTitle:'لم تتم الموافقة على المهرجان', greeting:'مرحبًا {{name}}،', approved:'يسعدنا إبلاغك بأن مهرجانك، {{festival}}، قد تمت الموافقة عليه بنجاح! بعد مراجعة دقيقة، تأكدنا من استيفاء جميع المعايير المطلوبة، وأصبحت فعاليتك جاهزة للنشر. يمكنك الآن مشاركة مهرجانك مع الجمهور وجذب الحضور. إذا كنت بحاجة إلى تحديث أي تفاصيل أو إلى مساعدة، فريقنا جاهز لدعمك. تهانينا على إرسالك الناجح، ونتطلع إلى رؤية مهرجانك يتحقق على أرض الواقع!', rejected:'شكرًا لك على تقديم مهرجانك، {{festival}}، للمراجعة. بعد دراسة متأنية، نأسف لإبلاغك بأنه لم تتم الموافقة على مهرجانك في الوقت الحالي. نقدّر جهودك وإبداعك، وهناك بعض المعايير التي يجب استيفاؤها قبل أن يمكن نشر المهرجان. فريقنا هنا لمساعدتك في أي أسئلة أو إرشادات تحتاجها.', notes:'ملاحظات المراجعة', notesIntro:'ستجد هنا معلومات مفيدة حول عملية المراجعة:' },
  },
  fa: {
    password: { title:'بازنشانی رمز عبور Eveenty', heading:'درخواست بازنشانی رمز عبور', hello:'سلام', body:'درخواستی برای بازنشانی رمز عبور حساب Eveenty شما دریافت شد. برای ادامه، کد تأیید زیر را در اپلیکیشن Eveenty وارد کنید:', ignoreBefore:'اگر این بازنشانی را درخواست نکرده‌اید، این ایمیل را نادیده بگیرید یا ', ignoreLink:'با تیم پشتیبانی تماس بگیرید', ignoreAfter:' فوراً.', sentTo:'این پیام به', copyright:'© Eveenty، 10 - 225 The East Mall Suite #1264 - تورنتو - ON - M9B 0A9' },
    refund: { title:'رسید بازپرداخت', headline:'خریدهای {{user}} از {{festival}} بازپرداخت شد', name:'نام مشتری', address:'آدرس مشتری', phone:'تلفن مشتری', email:'ایمیل مشتری', date:'تاریخ', payment:'روش پرداخت', creditCard:'کارت اعتباری', refunded:'اقلام بازپرداخت‌شده', success:'اقلام زیر با موفقیت بازپرداخت شدند. انتظار می‌رود مبلغ ظرف ۳ تا ۵ روز کاری در حساب شما نشان داده شود.', canceled:'اقلام لغوشده', canceledIntro:'اقلام زیر لغو شدند. چون رایگان بودند، بازپرداختی صادر نشد، اما دیگر معتبر نیستند.', id:'شناسه', item:'نام', type:'نوع', qty:'تعداد', cost:'هزینه', fees:'کارمزد پردازش', tax:'مالیات', total:'جمع', amount:'مبلغ', bank:'کارمزد بانک', totalRefunded:'جمع بازپرداختی' },
    reject: { user:'متأسفیم که اطلاع می‌دهیم ثبت‌نام شما برای رویداد {{festival}} در این مرحله تأیید نشد. برای سؤالات، لطفاً با برگزارکننده رویداد تماس بگیرید.', organizer:'سلام {{name}} 👋، یک ثبت‌نام بلیط برای رویداد شما رد شد.', admin:'سلام Eveenty 👋، یک ثبت‌نام بلیط رد شد.', alert:'این ثبت‌نام بلیت رد شده است.', status:'رد شده', registrationId:'شماره ثبت‌نام', registrationDate:'تاریخ و زمان ثبت‌نام', currentStatus:'وضعیت فعلی', reviewDeadline:'مهلت بررسی', name:'نام', email:'ایمیل', phone:'تلفن', ticketType:'نوع بلیط', ticketHolder:'دارنده بلیط' },
    approval: { title:'به‌روزرسانی بررسی جشنواره', approvedTitle:'جشنواره تأیید شد', rejectedTitle:'جشنواره تأیید نشد', greeting:'{{name}} عزیز، سلام،', approved:'با خوشحالی اطلاع می‌دهیم که جشنوارهٔ شما، {{festival}}، با موفقیت تأیید شد! پس از بررسی دقیق، مطمئن شدیم که همهٔ معیارهای لازم رعایت شده و رویداد شما آمادهٔ انتشار است. اکنون می‌توانید جشنواره را با دیگران به اشتراک بگذارید و مخاطب جذب کنید. اگر نیاز به به‌روزرسانی جزئیات یا پشتیبانی دارید، تیم ما در کنار شماست. تبریک به بابت ارسال موفق؛ مشتاق دیدن جشنوارهٔ شما هستیم!', rejected:'از اینکه جشنوارهٔ {{festival}} را برای بررسی ارسال کردید سپاسگزاریم. پس از بررسی دقیق، متأسفیم که در حال حاضر جشنوارهٔ شما تأیید نشده است. تلاش و خلاقیت شما را ارج می‌نهیم؛ برای انتشار جشنواره باید معیارهایی برآورده شود. تیم ما برای پاسخ به پرسش‌ها و راهنمایی در کنار شماست.', notes:'یادداشت‌های بررسی', notesIntro:'در اینجا اطلاعات مفیدی دربارهٔ فرایند بررسی می‌بینید:' },
  },
};

export function pilotText(locale, key) {
  return (PILOT_LOCALES[locale] || PILOT_LOCALES.en)[key];
}
