/** Safe sample payloads for Eveenty email preview — no production credentials. */

export const SAMPLE = {
  user: {
    displayName: 'Alex',
    fullName: 'Alex User',
    email: 'alex.user@example.com',
    phone: '+1 416 555 0199',
    address: '12 King St W, Toronto',
  },
  guest: {
    fullName: 'Jordan Guest',
    email: 'jordan.guest@example.com',
  },
  festival: {
    name: 'Summer Music Festival 2026',
    place: 'Harbourfront Centre',
    address: '235 Queens Quay W, Toronto, ON',
    mapUrl: 'https://maps.example.com/preview-harbourfront',
    doorsOpen: 'Sat, Oct 10, 2026 · 6:00 PM',
    start: 'Sat, Oct 10, 2026 · 7:00 PM',
    end: 'Sat, Oct 10, 2026 · 11:30 PM',
    timezoneNote: 'All times shown in America/Toronto timezone.',
  },
  money: {
    subtotal: 'CA$80.00',
    tax: 'CA$10.40',
    processingFee: 'CA$2.50',
    grandTotal: 'CA$92.90',
    invoiceId: 'INV-90421',
    date: '2026-09-20',
    time: '14:32',
  },
  ticket: {
    type: 'General Admission',
    id: 'TKT-18402',
    indexLabel: 'Ticket 1 / 2',
  },
  registration: {
    id: 'REG-77821',
    dateTime: 'Sep 18, 2026 · 3:45 PM',
    status: 'Pending Payment',
    paymentDeadline: 'Sep 25, 2026 · 11:59 PM',
    completeOrderUrl: 'https://example.com/preview/complete-order',
  },
  support: {
    environment: 'production',
    detailsDefault: `Error: timeout waiting for upstream
Path: POST /api/v1/festivals/{id}/tickets
Request ID: req_9f3a2c
Time: 2026-09-23T17:04:12Z`,
    detailsLong: `Error: timeout waiting for upstream service after 30s
Path: POST /api/v1/festivals/{id}/tickets
Request ID: req_9f3a2c_preview_sample
Time: 2026-09-23T17:04:12Z
Host: api-preview.eveenty.local (SAMPLE — not a real host)
Trace (sanitized SAMPLE stack — no secrets):
  at TicketService.Create (services/ticket.go:412)
  at Handler.PostTickets (api/tickets.go:188)
  at middleware.Recover (api/middleware.go:54)
  at http.Handler.ServeHTTP (net/http)
Note: This is synthetic long-content preview data. Do not treat as a production incident.`,
  },
  activate: {
    preheader: 'Activate your Eveenty account to get started.',
    activateUrl: 'https://example.com/preview/activate',
  },
  dispute: {
    reference: 'dp_sample_9f3a2c',
    reason: 'Fraudulent',
    evidenceDue: '2026-10-05',
    amount: 'CA$92.90',
    fees: 'CA$15.00',
    evidenceFees: 'CA$0.00',
    viewPaymentUrl: 'https://example.com/preview/stripe-payment',
  },
  marketing: {
    bodyText:
      'Join us at Summer Music Festival 2026 — early-bird weekend passes are open. SAMPLE campaign body from organizer (author content).',
    unsubscribeUrl: 'https://example.com/preview/unsubscribe',
  },
};

export const LOCALES = {
  en: {
    lang: 'en',
    dir: 'ltr',
    logo: 'en',
    activate: {
      title: 'Activate Your Eveenty Account',
      welcome: 'Welcome to Eveenty!',
      greeting: 'Hello',
      body: 'Thank you for creating your Eveenty account. To get started, please activate your account by clicking the button below.',
      button: 'Activate My Account',
      footerLead: 'This message was sent to',
      footerSuffix: '.',
      copyright: '© Eveenty. All rights reserved.',
    },
    donation: {
      title: 'Donation receipt',
      preheader: 'Your donation payment receipt for Summer Music Festival 2026',
      notTax: 'This is not a Tax receipt, this is just your payment receipt.',
      donatedTo: 'donated to',
      thankYou: (name, fest) => `Thank you ${name} for using Eveenty & your donation to ${fest}`,
      clientName: 'Client Name:',
      clientAddress: 'Client Address:',
      clientPhone: 'Client Phone:',
      clientEmail: 'Client Email:',
      invoiceId: 'Invoice ID:',
      date: 'Date:',
    },
    ticketSale: {
          "title": "Your tickets",
          "preheader": "Tickets — Summer Music Festival 2026",
          "hello": "Hello",
          "buyerNote": "We have received your registration for the event",
          "carry": "To claim your entry, please carry a copy of the below receipt with you to the event.",
          "guestBought": "has bought you a ticket at the",
          "asUser": "AS USER:",
          "boughtFor": "bought ticket(s) for",
          "qrCaption": "Present this QR at entry",
          "googleWallet": "Add to Google Wallet",
          "appleWallet": "Add to Apple Wallet",
          "addTo": "Add to:",
          "googleCal": "Google Calendar",
          "appleCal": "Apple Calendar",
          "yahooCal": "Yahoo Calendar",
          "attachTitle": "Attachments included",
          "attachBody": "Apple Wallet pass (.pkpass) attached when available for this ticket. [SAMPLE — no real pass generated]",
          "copyright": "© Eveenty, 10 - 225 The East Mall Suite #1264 - Toronto - ON - M9B 0A9"
    },
    dispute: {
          "title": "Dispute Notification",
          "preheader": "⚠️ New Dispute Alert",
          "greeting": "Dear",
          "alertNeedsResponse": "⚠️ New Dispute Alert",
          "statusNeedsResponse": "A new dispute has been filed for your event {{FEST}}. Please review the details below for your information.",
          "nextDefault": "Our team will review this dispute and handle the counter-dispute process on your behalf. Please share any details or notes regarding this transaction that you would like us to add to our counter dispute, otherwise no action is needed from your side.",
          "nextStripe": "As this transaction was processed through Stripe Connect, you are responsible for countering this dispute through your <strong>Stripe Dashboard</strong>. Please log in to your Stripe account, navigate to the Disputes section, submit your counter-dispute evidence, and share any relevant details with us. Our platform will not handle the counter-dispute process on your behalf.",
          "eventInfo": "Event Information",
          "eventName": "Event Name",
          "detailsTitle": "Dispute Details",
          "nextTitle": "What Happens Next",
          "needHelpTitle": "Need Help?",
          "field": "Field",
          "details": "Details",
          "userName": "User Name",
          "email": "Email Address",
          "phone": "Phone Number",
          "txnType": "Transaction Type",
          "reference": "Dispute Reference",
          "reason": "Dispute Reason",
          "evidenceDue": "Evidence Due By",
          "amount": "Disputed Amount",
          "fees": "Dispute Fees",
          "evidenceFees": "Dispute Evidence Fees",
          "needHelpText": "If you have any questions or need assistance, please contact us at",
          "bestRegards": "Best regards,",
          "teamName": "The Eveenty Team",
          "viewPayment": "View Payment in Stripe",
          "txnTickets": "Tickets"
    },
    regApproval: {
      title: 'Ticket registration approved',
      preheader: 'Your ticket registration has been approved — complete your order',
      alert: 'Your ticket registration has been approved. Please complete your order to secure your tickets.',
      greeting: (fest, deadline) =>
        `Great news! Your ticket registration for ${fest} has been approved. Complete your order below to secure your tickets. You must complete your order by ${deadline}. If you do not complete your order by this date, the registration will be automatically cancelled.`,
      summarySubtitle: 'Below is the registration summary for this submission.',
      completeOrder: 'Complete your order',
      summaryTitle: '📋 Registration Summary',
      buyerTitle: '👤 Buyer Information',
      ticketsTitle: '🎟️ Registered Tickets',
      ticketsSubtitle: 'Details for each ticket in this registration are listed below.',
      eventTitle: '📍 Event Details',
      eventSubtitle: 'When and where the event takes place.',
      viewMap: 'View Map →',
      footerTag: 'Make your event  ·  Eveenty',
      contactUs: 'Contact Us',
      autoNote: 'This is an automated notification from Eveenty.',
      help: 'Need help? Contact us at info@eveenty.com',
      copyright: '© Eveenty. All rights reserved.',
    },
    support: {
      title: 'Internal Server Error Notification',
      preheader: 'Internal server error notification',
      heading: 'Internal Server Error Notification',
      intro: 'An error occurred on the server. The details are as follows:',
      hint: 'This data might be helpful for fixing the error',
      footer1: 'Internal operational notification · Eveenty Ops',
      footer2: 'Do not forward outside the operations team.',
    },
    marketing: {
      title: 'Festival marketing',
      preheader: 'Festival campaign message',
    },
  },
  ar: {
    lang: 'ar',
    dir: 'rtl',
    logo: 'ar',
    activate: {
      title: 'قم بتفعيل حساب ايفينتي الخاص بك',
      welcome: 'مرحباً بك في ايفينتي',
      greeting: '،مرحباً',
      body: 'شكراً لإنشاء حساب ايفينتي الخاص بك. للبدء، يرجى تفعيل حسابك بالنقر على الزر أدناه.',
      button: 'تفعيل حسابي',
      footerLead: 'تم إرسال هذه الرسالة إلى',
      footerSuffix: '.',
      copyright: '.© ايفينتي. جميع الحقوق محفوظة',
    },
    donation: {
      title: 'إيصال التبرع',
      preheader: 'إيصال دفع التبرع لـ Summer Music Festival 2026',
      notTax: 'هذا ليس إيصالاً ضريبياً، هذا مجرد إيصال دفع.',
      donatedTo: 'تبرع إلى',
      thankYou: (name, fest) => `شكراً ${name} لاستخدام إيفينتي وتبرعك لـ ${fest}`,
      clientName: 'اسم العميل:',
      clientAddress: 'عنوان العميل:',
      clientPhone: 'هاتف العميل:',
      clientEmail: 'البريد الإلكتروني:',
      invoiceId: 'رقم الفاتورة:',
      date: 'التاريخ:',
    },
    ticketSale: {
          "title": "تذاكرك",
          "preheader": "Tickets — Summer Music Festival 2026",
          "hello": "مرحباً",
          "buyerNote": "لقد استلمنا تسجيلك في الفعالية",
          "carry": "لاستخدام تذكرتك، يرجى إحضار نسخة من الإيصال أدناه معك إلى الفعالية.",
          "guestBought": "اشترى لك تذكرة في فعالية",
          "asUser": "كمستخدم:",
          "boughtFor": "قام بشراء تذكرة/تذاكر لـ",
          "qrCaption": "اعرض رمز QR هذا عند الدخول",
          "googleWallet": "Add to Google Wallet",
          "appleWallet": "Add to Apple Wallet",
          "addTo": "أضف إلى:",
          "googleCal": "Google Calendar",
          "appleCal": "Apple Calendar",
          "yahooCal": "Yahoo Calendar",
          "attachTitle": "مرفقات مضمّنة",
          "attachBody": "Apple Wallet pass (.pkpass) attached when available for this ticket. [SAMPLE — no real pass generated]",
          "copyright": "© Eveenty، 10 - 225 The East Mall Suite #1264 - تورونتو - أونتاريو - M9B 0A9"
    },
    dispute: {
          "title": "إشعار نزاع",
          "preheader": "⚠️ تنبيه: نزاع جديد",
          "greeting": "مرحباً",
          "alertNeedsResponse": "⚠️ تنبيه: نزاع جديد",
          "statusNeedsResponse": "تم تقديم نزاع جديد بشأن فعاليتك {{FEST}}. يرجى مراجعة التفاصيل أدناه للاطلاع.",
          "nextDefault": "سيقوم فريقنا بمراجعة هذا النزاع والتعامل مع عملية الاعتراض نيابةً عنك. يرجى مشاركة أي تفاصيل أو ملاحظات تتعلق بهذه المعاملة تودّ إضافتها إلى اعتراضنا، وإلا فلا حاجة لأي إجراء من جانبك.",
          "nextStripe": "نظراً لأن هذه المعاملة تمت معالجتها عبر Stripe Connect، فأنت مسؤول عن الرد على هذا النزاع من خلال <strong>لوحة تحكم Stripe</strong> الخاصة بك. يرجى تسجيل الدخول إلى حساب Stripe الخاص بك، والانتقال إلى قسم النزاعات، وتقديم أدلة الاعتراض، ومشاركة أي تفاصيل ذات صلة معنا. لن تتولى منصتنا عملية الاعتراض نيابةً عنك.",
          "eventInfo": "معلومات الفعالية",
          "eventName": "اسم الفعالية",
          "detailsTitle": "تفاصيل النزاع",
          "nextTitle": "ما الذي سيحدث بعد ذلك",
          "needHelpTitle": "هل تحتاج إلى مساعدة؟",
          "field": "الحقل",
          "details": "التفاصيل",
          "userName": "اسم المستخدم",
          "email": "البريد الإلكتروني",
          "phone": "رقم الهاتف",
          "txnType": "نوع المعاملة",
          "reference": "مرجع النزاع",
          "reason": "سبب النزاع",
          "evidenceDue": "آخر موعد لتقديم الأدلة",
          "amount": "المبلغ المتنازع عليه",
          "fees": "رسوم النزاع",
          "evidenceFees": "رسوم أدلة النزاع",
          "needHelpText": "إذا كانت لديك أي أسئلة أو تحتاج إلى مساعدة، يرجى التواصل معنا على",
          "bestRegards": "مع أطيب التحيات،",
          "teamName": "فريق Eveenty",
          "viewPayment": "عرض المعاملة في سترايب",
          "txnTickets": "تذاكر"
    },
    regApproval: {
      title: 'تمت الموافقة على التسجيل',
      preheader: 'تمت الموافقة على تسجيل التذكرة — أكمل طلبك',
      alert: 'تمت الموافقة على تسجيل تذكرتك. يرجى إكمال طلبك لتأمين تذاكرك.',
      greeting: (fest, deadline) =>
        `أخبار سارة! تمت الموافقة على تسجيل تذكرتك لـ ${fest}. أكمل طلبك أدناه لتأمين تذاكرك. يجب إكمال الطلب بحلول ${deadline}. إذا لم تكمل الطلب بحلول هذا التاريخ، سيتم إلغاء التسجيل تلقائياً.`,
      summarySubtitle: 'فيما يلي ملخص التسجيل لهذا الإرسال.',
      completeOrder: 'أكمل طلبك',
      summaryTitle: '📋 ملخص التسجيل',
      buyerTitle: '👤 معلومات المشتري',
      ticketsTitle: '🎟️ التذاكر المسجّلة',
      ticketsSubtitle: 'تفاصيل كل تذكرة في هذا التسجيل مدرجة أدناه.',
      eventTitle: '📍 تفاصيل الفعالية',
      eventSubtitle: 'متى وأين تقام الفعالية.',
      viewMap: 'عرض الخريطة ←',
      footerTag: 'اصنع فعاليتك  ·  إيفينتي',
      contactUs: 'تواصل معنا',
      autoNote: 'هذا إشعار تلقائي من إيفينتي.',
      help: 'تحتاج مساعدة؟ تواصل معنا على info@eveenty.com',
      copyright: '© إيفينتي. جميع الحقوق محفوظة.',
    },
    support: null,
    marketing: null,
  },
  fa: {
    lang: 'fa',
    dir: 'rtl',
    logo: 'fa',
    activate: {
      title: 'حساب Eveenty خود را فعال کنید',
      welcome: '!به Eveenty خوش آمدید',
      greeting: '،سلام',
      body: 'از ایجاد حساب Eveenty خود متشکریم. برای شروع، لطفاً با کلیک بر روی دکمه زیر حساب خود را فعال کنید.',
      button: 'فعال‌سازی حساب من',
      footerLead: 'این پیام به',
      footerSuffix: ' ارسال شد.',
      copyright: '.© Eveenty. تمامی حقوق محفوظ است',
    },
    donation: {
      title: 'رسید کمک مالی',
      preheader: 'رسید پرداخت کمک مالی برای Summer Music Festival 2026',
      notTax: 'این رسید مالیاتی نیست؛ فقط رسید پرداخت است.',
      donatedTo: 'کمک مالی به',
      thankYou: (name, fest) => `متشکریم ${name} از استفاده از ایونتی و کمک شما به ${fest}`,
      clientName: 'نام مشتری:',
      clientAddress: 'آدرس مشتری:',
      clientPhone: 'تلفن مشتری:',
      clientEmail: 'ایمیل مشتری:',
      invoiceId: 'شناسه فاکتور:',
      date: 'تاریخ:',
    },
    ticketSale: {
          "title": "بلیت‌های شما",
          "preheader": "Tickets — Summer Music Festival 2026",
          "hello": "سلام",
          "buyerNote": "ثبت‌نام شما در رویداد دریافت شد",
          "carry": "برای ورود به رویداد، لطفاً یک نسخه از رسید زیر را همراه خود داشته باشید.",
          "guestBought": "برای شما بلیت رویداد",
          "asUser": "به عنوان کاربر:",
          "boughtFor": "بلیت(ها) را برای رویداد",
          "qrCaption": "این QR را در ورودی نشان دهید",
          "googleWallet": "Add to Google Wallet",
          "appleWallet": "Add to Apple Wallet",
          "addTo": "افزودن به:",
          "googleCal": "Google Calendar",
          "appleCal": "Apple Calendar",
          "yahooCal": "Yahoo Calendar",
          "attachTitle": "پیوست‌ها",
          "attachBody": "Apple Wallet pass (.pkpass) attached when available for this ticket. [SAMPLE — no real pass generated]",
          "copyright": "© Eveenty، 10 - 225 The East Mall Suite #1264 - تورنتو - ON - M9B 0A9"
    },
    dispute: {
          "title": "اطلاعیه اعتراض",
          "preheader": "⚠️ هشدار: اعتراض جدید",
          "greeting": "با سلام",
          "alertNeedsResponse": "⚠️ هشدار: اعتراض جدید",
          "statusNeedsResponse": "یک اعتراض جدید برای رویداد شما {{FEST}} ثبت شده است. لطفاً جزئیات زیر را برای اطلاع خود مرور کنید.",
          "nextDefault": "تیم ما این اعتراض را بررسی کرده و فرآیند پاسخ به اعتراض را از طرف شما مدیریت خواهد کرد. لطفاً هر گونه جزئیات یا یادداشتی درباره این تراکنش که می‌خواهید به پاسخ ما اضافه شود را با ما در میان بگذارید؛ در غیر این صورت نیازی به هیچ اقدامی از جانب شما نیست.",
          "nextStripe": "از آنجا که این تراکنش از طریق Stripe Connect پردازش شده است، شما مسئول پاسخ به این اعتراض از طریق <strong>داشبورد Stripe</strong> خود هستید. لطفاً به حساب Stripe خود وارد شوید، به بخش اختلافات بروید، مدارک پاسخ به اعتراض را ارسال کنید و هر گونه جزئیات مرتبط را با ما در میان بگذارید. پلتفرم ما فرآیند پاسخ به اعتراض را از طرف شما انجام نخواهد داد.",
          "eventInfo": "اطلاعات رویداد",
          "eventName": "نام رویداد",
          "detailsTitle": "جزئیات اعتراض",
          "nextTitle": "مراحل بعدی",
          "needHelpTitle": "نیاز به کمک دارید؟",
          "field": "فیلد",
          "details": "جزئیات",
          "userName": "نام کاربر",
          "email": "آدرس ایمیل",
          "phone": "شماره تلفن",
          "txnType": "نوع تراکنش",
          "reference": "شماره مرجع اعتراض",
          "reason": "دلیل اعتراض",
          "evidenceDue": "مدارک باید تا این تاریخ ارسال شود",
          "amount": "مبلغ مورد اعتراض",
          "fees": "هزینه‌های اعتراض",
          "evidenceFees": "هزینه‌های مدارک اعتراض",
          "needHelpText": "اگر سؤال یا نیاز به کمک دارید، لطفاً با ما از طریق ایمیل تماس بگیرید",
          "bestRegards": "با احترام،",
          "teamName": "تیم Eveenty",
          "viewPayment": "مشاهده پرداخت در سترايب",
          "txnTickets": "بلیط‌ها"
    },
    regApproval: {
      title: 'ثبت‌نام تأیید شد',
      preheader: 'ثبت‌نام بلیت تأیید شد — سفارش را کامل کنید',
      alert: 'ثبت‌نام بلیت شما تأیید شد. لطفاً سفارش را کامل کنید تا بلیت‌ها محفوظ بمانند.',
      greeting: (fest, deadline) =>
        `خبر خوب! ثبت‌نام بلیت شما برای ${fest} تأیید شد. سفارش را در زیر کامل کنید. باید تا ${deadline} سفارش را کامل کنید؛ در غیر این صورت ثبت‌نام لغو می‌شود.`,
      summarySubtitle: 'خلاصه ثبت‌نام این ارسال در زیر آمده است.',
      completeOrder: 'تکمیل سفارش',
      summaryTitle: '📋 خلاصه ثبت‌نام',
      buyerTitle: '👤 اطلاعات خریدار',
      ticketsTitle: '🎟️ بلیت‌های ثبت‌شده',
      ticketsSubtitle: 'جزئیات هر بلیت در زیر فهرست شده است.',
      eventTitle: '📍 جزئیات رویداد',
      eventSubtitle: 'زمان و مکان برگزاری رویداد.',
      viewMap: 'مشاهده نقشه ←',
      footerTag: 'رویداد بسازید  ·  ایونتی',
      contactUs: 'تماس با ما',
      autoNote: 'این یک اعلان خودکار از ایونتی است.',
      help: 'نیاز به کمک؟ با info@eveenty.com تماس بگیرید',
      copyright: '© ایونتی. تمامی حقوق محفوظ است.',
    },
    support: null,
    marketing: null,
  },
  fr: {
    lang: 'fr',
    dir: 'ltr',
    logo: 'fr',
    activate: {
      title: 'Activez votre compte Eveenty',
      welcome: 'Bienvenue sur Eveenty !',
      greeting: 'Bonjour',
      body: "Merci d'avoir créé votre compte Eveenty. Pour commencer, veuillez activer votre compte en cliquant sur le bouton ci-dessous.",
      button: 'Activer mon compte',
      footerLead: 'Ce message a été envoyé à',
      footerSuffix: '.',
      copyright: '© Eveenty. Tous droits réservés.',
    },
    donation: {
      title: "Facture",
      preheader: "Votre reçu de paiement de don pour Summer Music Festival 2026",
      notTax: "Ceci n'est pas un reçu fiscal, c'est simplement votre reçu de paiement.",
      donatedTo: "a fait un don à",
      thankYou: (name, fest) => "Merci" + ' ' + name + ' ' + "d'utiliser Eveenty et pour votre don à" + ' ' + fest,
      clientName: "Nom du client :",
      clientAddress: "Adresse du client :",
      clientPhone: "Téléphone du client :",
      clientEmail: "Courriel du client :",
      invoiceId: "Facture n° :",
      date: "Date :",
    },
    ticketSale: {
          "title": "Vos billets",
          "preheader": "Tickets — Summer Music Festival 2026",
          "hello": "Bonjour",
          "buyerNote": "Nous avons bien reçu votre inscription à l'événement",
          "carry": "Pour accéder à l'événement, veuillez apporter une copie du reçu ci-dessous.",
          "guestBought": "vous a acheté un billet pour l'événement",
          "asUser": "EN TANT QU'UTILISATEUR :",
          "boughtFor": "a acheté des billet(s) pour",
          "qrCaption": "Présentez ce QR à l'entrée",
          "googleWallet": "Add to Google Wallet",
          "appleWallet": "Add to Apple Wallet",
          "addTo": "Ajouter à :",
          "googleCal": "Google Agenda",
          "appleCal": "Calendrier Apple",
          "yahooCal": "Calendrier Yahoo",
          "attachTitle": "Pièces jointes",
          "attachBody": "Apple Wallet pass (.pkpass) attached when available for this ticket. [SAMPLE — no real pass generated]",
          "copyright": "© Eveenty, 10 - 225 The East Mall Suite #1264 - Toronto - ON - M9B 0A9"
    },
    dispute: {
          "title": "Notification de Litige",
          "preheader": "⚠️ Nouvelle Alerte de Litige",
          "greeting": "Cher/Chère",
          "alertNeedsResponse": "⚠️ Nouvelle Alerte de Litige",
          "statusNeedsResponse": "Un nouveau litige a été déposé pour votre événement {{FEST}}. Veuillez consulter les détails ci-dessous pour votre information.",
          "nextDefault": "Notre équipe examinera ce litige et gérera le processus de contre-litige en votre nom. Veuillez partager tout détail ou note concernant cette transaction que vous souhaiteriez que nous ajoutions à notre contre-litige ; sinon, aucune action n'est requise de votre part.",
          "nextStripe": "Comme cette transaction a été traitée via Stripe Connect, vous êtes responsable de répondre à ce litige via votre <strong>tableau de bord Stripe</strong>. Connectez-vous à votre compte Stripe, accédez à la section Litiges, soumettez vos preuves de contre-litige et partagez tout détail pertinent avec nous. Notre plateforme ne gérera pas le processus de contre-litige en votre nom.",
          "eventInfo": "Informations sur l'Événement",
          "eventName": "Nom de l'Événement",
          "detailsTitle": "Détails du Litige",
          "nextTitle": "Que Se Passe-t-il Ensuite ?",
          "needHelpTitle": "Besoin d'Aide ?",
          "field": "Champ",
          "details": "Détails",
          "userName": "Nom de l'Utilisateur",
          "email": "Adresse E-mail",
          "phone": "Numéro de Téléphone",
          "txnType": "Type de Transaction",
          "reference": "Référence du Litige",
          "reason": "Motif du Litige",
          "evidenceDue": "Preuves à soumettre avant le",
          "amount": "Montant Contesté",
          "fees": "Frais de Litige",
          "evidenceFees": "Frais de Preuves du Litige",
          "needHelpText": "Si vous avez des questions ou avez besoin d'assistance, veuillez nous contacter à",
          "bestRegards": "Cordialement,",
          "teamName": "L'Équipe Eveenty",
          "viewPayment": "Voir le paiement dans Stripe",
          "txnTickets": "Billets"
    },
    regApproval: {
      title: "Inscription de billet approuvée",
      preheader: "Votre inscription a été approuvée. Veuillez finaliser votre commande pour confirmer vos billets.",
      alert: "Votre inscription a été approuvée. Veuillez finaliser votre commande pour confirmer vos billets.",
      greeting: (fest, deadline) => `Bonne nouvelle ! Votre inscription pour l'événement ${fest} a été approuvée. Finalisez votre commande ci-dessous pour sécuriser vos billets. Vous devez finaliser votre commande avant le ${deadline}. Passé ce délai, l'inscription sera automatiquement annulée.`,
      summarySubtitle: "Voici le résumé de cette inscription.",
      completeOrder: "Finaliser votre commande",
      summaryTitle: "📋 Résumé de l'inscription",
      buyerTitle: "👤 Informations de l'acheteur",
      ticketsTitle: "🎟️ Billets inscrits",
      ticketsSubtitle: "Les détails de chaque billet de cette inscription sont listés ci-dessous.",
      eventTitle: "📍 Détails de l'événement",
      eventSubtitle: "Quand et où se déroule l'événement.",
      viewMap: "Voir la carte →",
      footerTag: "Créez votre événement  ·  Eveenty",
      contactUs: "Contactez-nous",
      autoNote: "Ceci est une notification automatique d'Eveenty.",
      help: "Besoin d'aide ? Contactez-nous à info@eveenty.com",
      copyright: "© Eveenty. Tous droits réservés.",
    },
    support: null,
    marketing: null,
  },
  es: {
    lang: 'es',
    dir: 'ltr',
    logo: 'es',
    activate: {
      title: 'Active su cuenta Eveenty',
      welcome: '¡Bienvenido a Eveenty!',
      greeting: 'Hola',
      body: 'Gracias por crear su cuenta Eveenty. Para comenzar, active su cuenta haciendo clic en el botón a continuación.',
      button: 'Activar mi cuenta',
      footerLead: 'Este mensaje fue enviado a',
      footerSuffix: '.',
      copyright: '© Eveenty. Todos los derechos reservados.',
    },
    donation: {
      title: "Factura",
      preheader: "Su recibo de pago de donación para Summer Music Festival 2026",
      notTax: "Esto no es un recibo fiscal, es solo su recibo de pago.",
      donatedTo: "donó a",
      thankYou: (name, fest) => "Gracias" + ' ' + name + ' ' + "por usar Eveenty y por su donación a" + ' ' + fest,
      clientName: "Nombre del cliente:",
      clientAddress: "Dirección del cliente:",
      clientPhone: "Teléfono del cliente:",
      clientEmail: "Correo del cliente:",
      invoiceId: "ID de factura:",
      date: "Fecha:",
    },
    ticketSale: {
          "title": "Tus entradas",
          "preheader": "Tickets — Summer Music Festival 2026",
          "hello": "Hola",
          "buyerNote": "Hemos recibido tu registro para el evento",
          "carry": "Para reclamar tu entrada, por favor lleva una copia del siguiente recibo al evento.",
          "guestBought": "te ha comprado una entrada para el evento",
          "asUser": "COMO USUARIO:",
          "boughtFor": "compró entrada(s) para",
          "qrCaption": "Presenta este QR en la entrada",
          "googleWallet": "Add to Google Wallet",
          "appleWallet": "Add to Apple Wallet",
          "addTo": "Agregar a:",
          "googleCal": "Google Calendar",
          "appleCal": "Calendario Apple",
          "yahooCal": "Calendario Yahoo",
          "attachTitle": "Adjuntos",
          "attachBody": "Apple Wallet pass (.pkpass) attached when available for this ticket. [SAMPLE — no real pass generated]",
          "copyright": "© Eveenty, 10 - 225 The East Mall Suite #1264 - Toronto - ON - M9B 0A9"
    },
    dispute: {
          "title": "Notificación de Disputa",
          "preheader": "⚠️ Nueva Alerta de Disputa",
          "greeting": "Estimado/a",
          "alertNeedsResponse": "⚠️ Nueva Alerta de Disputa",
          "statusNeedsResponse": "Se ha presentado una nueva disputa para tu evento {{FEST}}. Por favor, revisa los detalles a continuación para tu información.",
          "nextDefault": "Nuestro equipo revisará esta disputa y gestionará el proceso de contra-disputa en tu nombre. Por favor, comparte cualquier detalle o nota sobre esta transacción que desees que agreguemos a nuestra contra-disputa; de lo contrario, no se requiere ninguna acción de tu parte.",
          "nextStripe": "Como esta transacción se procesó a través de Stripe Connect, usted es responsable de responder a esta disputa desde su <strong>Panel de Stripe</strong>. Inicie sesión en su cuenta de Stripe, navegue a la sección de Disputas, envíe su evidencia de contra-disputa y comparta cualquier detalle relevante con nosotros. Nuestra plataforma no gestionará el proceso de contra-disputa en su nombre.",
          "eventInfo": "Información del Evento",
          "eventName": "Nombre del Evento",
          "detailsTitle": "Detalles de la Disputa",
          "nextTitle": "¿Qué Sucede a Continuación?",
          "needHelpTitle": "¿Necesitas Ayuda?",
          "field": "Campo",
          "details": "Detalles",
          "userName": "Nombre del Usuario",
          "email": "Correo Electrónico",
          "phone": "Número de Teléfono",
          "txnType": "Tipo de Transacción",
          "reference": "Referencia de la Disputa",
          "reason": "Motivo de la Disputa",
          "evidenceDue": "Evidencia debe presentarse antes del",
          "amount": "Monto Disputado",
          "fees": "Tarifas de la Disputa",
          "evidenceFees": "Tarifas de Evidencia de la Disputa",
          "needHelpText": "Si tienes alguna pregunta o necesitas asistencia, por favor contáctanos en",
          "bestRegards": "Atentamente,",
          "teamName": "El Equipo de Eveenty",
          "viewPayment": "Ver pago en Stripe",
          "txnTickets": "Entradas"
    },
    regApproval: {
      title: "Inscripción de entrada aprobada",
      preheader: "Su inscripción ha sido aprobada. Complete su pedido para finalizar la compra de sus entradas.",
      alert: "Su inscripción ha sido aprobada. Complete su pedido para finalizar la compra de sus entradas.",
      greeting: (fest, deadline) => `¡Buenas noticias! Tu inscripción para el evento ${fest} ha sido aprobada. Completa tu pedido a continuación para asegurar tus entradas. Debes completar tu pedido antes del ${deadline}. Si no lo completas antes de esa fecha, la inscripción será cancelada automáticamente.`,
      summarySubtitle: "A continuación se muestra el resumen de esta inscripción.",
      completeOrder: "Completar su pedido",
      summaryTitle: "📋 Resumen de inscripción",
      buyerTitle: "👤 Información del comprador",
      ticketsTitle: "🎟️ Entradas inscritas",
      ticketsSubtitle: "A continuación se muestran los detalles de cada entrada en esta inscripción.",
      eventTitle: "📍 Detalles del evento",
      eventSubtitle: "Cuándo y dónde se celebra el evento.",
      viewMap: "Ver mapa →",
      footerTag: "Haz tu evento  ·  Eveenty",
      contactUs: "Contáctenos",
      autoNote: "Esta es una notificación automática de Eveenty.",
      help: "¿Necesitas ayuda? Contáctanos en info@eveenty.com",
      copyright: "© Eveenty. Todos los derechos reservados.",
    },
    support: null,
    marketing: null,
  },
};

export const EMAIL_IDS = [
  {
    id: 'activate_email',
    label: 'Auth / Simple — activate_email',
    master: 'TRANSACTIONAL',
    figma: '4:2',
    locales: ['en', 'fr', 'es', 'ar', 'fa'],
    variants: ['default'],
  },
  {
    id: 'festival_donation',
    label: 'Financial / Receipt — festival_donation',
    master: 'COMMERCE',
    figma: '21:2',
    locales: ['en', 'fr', 'es', 'ar', 'fa'],
    variants: ['donatorUser', 'organizerNotify'],
  },
  {
    id: 'festival_ticket_sale',
    label: 'Ticket / Pass — festival_ticket_sale',
    master: 'COMMERCE',
    figma: '21:53',
    locales: ['en', 'fr', 'es', 'ar', 'fa'],
    variants: ['buyerUser', 'guestUser', 'organizer', 'admin'],
  },
  {
    id: 'festival_ticket_registration_approval',
    label: 'Workflow / Status — registration_approval',
    master: 'COMMERCE / Ticket-Pass',
    figma: '48:45',
    locales: ['en', 'fr', 'es', 'ar', 'fa'],
    variants: ['user_completeOrder', 'user_noCta'],
  },
  {
    id: 'support',
    label: 'Internal / Operational — support',
    master: 'NOTIFICATION',
    figma: '22:113',
    locales: ['en'],
    variants: ['default', 'longDetails'],
  },
  {
    id: 'dispute_notification',
    label: 'Workflow / Status — dispute_notification',
    master: 'NOTIFICATION',
    figma: '72:44',
    locales: ['en', 'fr', 'es', 'ar', 'fa'],
    variants: ['organizer', 'admin', 'withPaymentLink', 'stripeConnect', 'noEvidence'],
  },
  {
    id: 'festival_marketing_email_target',
    label: 'Campaign / Announcement — festival_marketing_email_target',
    master: 'MARKETING',
    figma: '72:175',
    locales: ['en'],
    variants: ['default'],
  },
];
