/** Safe sample payloads for Eveenty email preview — no production credentials. */

export const SAMPLE = {
  user: {
    displayName: 'Alex',
    fullName: 'Alex User',
    email: 'alex.user@example.com',
    phone: '+1 416 555 0199',
    address: '12 King St W, Toronto',
  },
  guest: {
    fullName: 'Jordan Guest',
    email: 'jordan.guest@example.com',
  },
  festival: {
    name: 'Summer Music Festival 2026',
    place: 'Harbourfront Centre',
    address: '235 Queens Quay W, Toronto, ON',
    mapUrl: 'https://maps.example.com/preview-harbourfront',
    doorsOpen: 'Sat, Oct 10, 2026 · 6:00 PM',
    start: 'Sat, Oct 10, 2026 · 7:00 PM',
    end: 'Sat, Oct 10, 2026 · 11:30 PM',
    timezoneNote: 'All times shown in America/Toronto timezone.',
  },
  money: {
    subtotal: 'CA$80.00',
    tax: 'CA$10.40',
    processingFee: 'CA$2.50',
    grandTotal: 'CA$92.90',
    invoiceId: 'INV-90421',
    date: '2026-09-20',
    time: '14:32',
  },
  ticket: {
    type: 'General Admission',
    id: 'TKT-18402',
    indexLabel: 'Ticket 1 / 2',
  },
  registration: {
    id: 'REG-77821',
    dateTime: 'Sep 18, 2026 · 3:45 PM',
    status: 'Pending Payment',
    paymentDeadline: 'Sep 25, 2026 · 11:59 PM',
    completeOrderUrl: 'https://example.com/preview/complete-order',
  },
  support: {
    environment: 'production',
    detailsDefault: `Error: timeout waiting for upstream
Path: POST /api/v1/festivals/{id}/tickets
Request ID: req_9f3a2c
Time: 2026-09-23T17:04:12Z`,
    detailsLong: `Error: timeout waiting for upstream service after 30s
Path: POST /api/v1/festivals/{id}/tickets
Request ID: req_9f3a2c_preview_sample
Time: 2026-09-23T17:04:12Z
Host: api-preview.eveenty.local (SAMPLE — not a real host)
Trace (sanitized SAMPLE stack — no secrets):
  at TicketService.Create (services/ticket.go:412)
  at Handler.PostTickets (api/tickets.go:188)
  at middleware.Recover (api/middleware.go:54)
  at http.Handler.ServeHTTP (net/http)
Note: This is synthetic long-content preview data. Do not treat as a production incident.`,
  },
  activate: {
    preheader: 'Activate your Eveenty account to get started.',
    activateUrl: 'https://example.com/preview/activate',
  },
};

export const LOCALES = {
  en: {
    lang: 'en',
    dir: 'ltr',
    logo: 'en',
    activate: {
      // Exact strings from pkg/locales/translations/email/en.yaml (ActivateEmail*)
      title: 'Activate Your Eveenty Account',
      welcome: 'Welcome to Eveenty!',
      greeting: 'Hello',
      body: 'Thank you for creating your Eveenty account. To get started, please activate your account by clicking the button below.',
      button: 'Activate My Account',
      footerLead: 'This message was sent to',
      footerSuffix: '.',
      copyright: '© Eveenty. All rights reserved.',
    },
    donation: {
      title: 'Donation receipt',
      preheader: 'Your donation payment receipt for Summer Music Festival 2026',
      notTax: 'This is not a Tax receipt, this is just your payment receipt.',
      thankYou: (name, fest) => `Thank you ${name} for using Eveenty & your donation to ${fest}`,
      clientName: 'Client Name:',
      clientAddress: 'Client Address:',
      clientPhone: 'Client Phone:',
      clientEmail: 'Client Email:',
      invoiceId: 'Invoice ID:',
      date: 'Date:',
    },
    ticketSale: {
      title: 'Your tickets',
      preheader: 'Your tickets for Summer Music Festival 2026',
      hello: 'Hello',
      received: (fest) => `We have received your registration for the event ${fest}.`,
      carry: 'To claim your entry, please carry a copy of the below receipt with you to the event.',
      qrCaption: 'Present this QR at entry',
      googleWallet: 'Add to Google Wallet',
      appleWallet: 'Add to Apple Wallet',
      calendar: 'Add to calendar: Google  |  Apple  |  Yahoo',
      attachTitle: 'Attachments included',
      attachBody: 'Apple Wallet pass (.pkpass) attached when available for this ticket. [SAMPLE — no real pass generated]',
    },
    regApproval: {
      title: 'Ticket registration approved',
      preheader: 'Your ticket registration has been approved — complete your order',
      alert: 'Your ticket registration has been approved. Please complete your order to secure your tickets.',
      greeting: (fest, deadline) =>
        `Great news! Your ticket registration for ${fest} has been approved. Complete your order below to secure your tickets. You must complete your order by ${deadline}. If you do not complete your order by this date, the registration will be automatically cancelled.`,
      summarySubtitle: 'Below is the registration summary for this submission.',
      completeOrder: 'Complete your order',
      summaryTitle: '📋 Registration Summary',
      buyerTitle: '👤 Buyer Information',
      ticketsTitle: '🎟️ Registered Tickets',
      ticketsSubtitle: 'Details for each ticket in this registration are listed below.',
      eventTitle: '📍 Event Details',
      eventSubtitle: 'When and where the event takes place.',
      viewMap: 'View Map →',
      footerTag: 'Make your event  ·  Eveenty',
      contactUs: 'Contact Us',
      autoNote: 'This is an automated notification from Eveenty.',
      help: 'Need help? Contact us at info@eveenty.com',
      copyright: '© Eveenty. All rights reserved.',
    },
    support: {
      title: 'Internal Server Error Notification',
      preheader: 'Internal server error notification',
      heading: 'Internal Server Error Notification',
      intro: 'An error occurred on the server. The details are as follows:',
      hint: 'This data might be helpful for fixing the error',
      footer1: 'Internal operational notification · Eveenty Ops',
      footer2: 'Do not forward outside the operations team.',
    },
  },
  ar: {
    lang: 'ar',
    dir: 'rtl',
    logo: 'ar',
    activate: {
      // Exact strings from pkg/locales/translations/email/ar.yaml (ActivateEmail*)
      title: 'قم بتفعيل حساب ايفينتي الخاص بك',
      welcome: 'مرحباً بك في ايفينتي',
      greeting: '،مرحباً',
      body: 'شكراً لإنشاء حساب ايفينتي الخاص بك. للبدء، يرجى تفعيل حسابك بالنقر على الزر أدناه.',
      button: 'تفعيل حسابي',
      footerLead: 'تم إرسال هذه الرسالة إلى',
      footerSuffix: '.',
      copyright: '.© ايفينتي. جميع الحقوق محفوظة',
    },
    donation: {
      title: 'إيصال التبرع',
      preheader: 'إيصال دفع التبرع لـ Summer Music Festival 2026',
      notTax: 'هذا ليس إيصالاً ضريبياً، هذا مجرد إيصال دفع.',
      thankYou: (name, fest) => `شكراً ${name} لاستخدام إيفينتي وتبرعك لـ ${fest}`,
      clientName: 'اسم العميل:',
      clientAddress: 'عنوان العميل:',
      clientPhone: 'هاتف العميل:',
      clientEmail: 'البريد الإلكتروني:',
      invoiceId: 'رقم الفاتورة:',
      date: 'التاريخ:',
    },
    ticketSale: {
      title: 'تذاكرك',
      preheader: 'تذاكرك لـ Summer Music Festival 2026',
      hello: 'مرحباً',
      received: (fest) => `لقد استلمنا تسجيلك لفعالية ${fest}.`,
      carry: 'للحصول على الدخول، يرجى إحضار نسخة من الإيصال أدناه إلى الفعالية.',
      qrCaption: 'اعرض رمز QR هذا عند الدخول',
      googleWallet: 'إضافة إلى Google Wallet',
      appleWallet: 'إضافة إلى Apple Wallet',
      calendar: 'إضافة إلى التقويم: Google  |  Apple  |  Yahoo',
      attachTitle: 'مرفقات مضمّنة',
      attachBody: 'مرفق Apple Wallet (.pkpass) عند التوفر. [عينة — لا تصاريح حقيقية]',
    },
    regApproval: {
      title: 'تمت الموافقة على التسجيل',
      preheader: 'تمت الموافقة على تسجيل التذكرة — أكمل طلبك',
      alert: 'تمت الموافقة على تسجيل تذكرتك. يرجى إكمال طلبك لتأمين تذاكرك.',
      greeting: (fest, deadline) =>
        `أخبار سارة! تمت الموافقة على تسجيل تذكرتك لـ ${fest}. أكمل طلبك أدناه لتأمين تذاكرك. يجب إكمال الطلب بحلول ${deadline}. إذا لم تكمل الطلب بحلول هذا التاريخ، سيتم إلغاء التسجيل تلقائياً.`,
      summarySubtitle: 'فيما يلي ملخص التسجيل لهذا الإرسال.',
      completeOrder: 'أكمل طلبك',
      summaryTitle: '📋 ملخص التسجيل',
      buyerTitle: '👤 معلومات المشتري',
      ticketsTitle: '🎟️ التذاكر المسجّلة',
      ticketsSubtitle: 'تفاصيل كل تذكرة في هذا التسجيل مدرجة أدناه.',
      eventTitle: '📍 تفاصيل الفعالية',
      eventSubtitle: 'متى وأين تقام الفعالية.',
      viewMap: 'عرض الخريطة ←',
      footerTag: 'اصنع فعاليتك  ·  إيفينتي',
      contactUs: 'تواصل معنا',
      autoNote: 'هذا إشعار تلقائي من إيفينتي.',
      help: 'تحتاج مساعدة؟ تواصل معنا على info@eveenty.com',
      copyright: '© إيفينتي. جميع الحقوق محفوظة.',
    },
    support: null, // EN-only
  },
  fa: {
    lang: 'fa',
    dir: 'rtl',
    logo: 'fa',
    activate: {
      // Exact strings from pkg/locales/translations/email/fa.yaml (ActivateEmail*)
      title: 'حساب Eveenty خود را فعال کنید',
      welcome: '!به Eveenty خوش آمدید',
      greeting: '،سلام',
      body: 'از ایجاد حساب Eveenty خود متشکریم. برای شروع، لطفاً با کلیک بر روی دکمه زیر حساب خود را فعال کنید.',
      button: 'فعال‌سازی حساب من',
      footerLead: 'این پیام به',
      footerSuffix: ' ارسال شد.',
      copyright: '.© Eveenty. تمامی حقوق محفوظ است',
    },
    donation: {
      title: 'رسید کمک مالی',
      preheader: 'رسید پرداخت کمک مالی برای Summer Music Festival 2026',
      notTax: 'این رسید مالیاتی نیست؛ فقط رسید پرداخت است.',
      thankYou: (name, fest) => `متشکریم ${name} از استفاده از ایونتی و کمک شما به ${fest}`,
      clientName: 'نام مشتری:',
      clientAddress: 'آدرس مشتری:',
      clientPhone: 'تلفن مشتری:',
      clientEmail: 'ایمیل مشتری:',
      invoiceId: 'شناسه فاکتور:',
      date: 'تاریخ:',
    },
    ticketSale: {
      title: 'بلیت‌های شما',
      preheader: 'بلیت‌های شما برای Summer Music Festival 2026',
      hello: 'سلام',
      received: (fest) => `ثبت‌نام شما برای رویداد ${fest} دریافت شد.`,
      carry: 'برای ورود، لطفاً نسخه‌ای از رسید زیر را همراه داشته باشید.',
      qrCaption: 'این QR را در ورودی نشان دهید',
      googleWallet: 'افزودن به Google Wallet',
      appleWallet: 'افزودن به Apple Wallet',
      calendar: 'افزودن به تقویم: Google  |  Apple  |  Yahoo',
      attachTitle: 'پیوست‌ها',
      attachBody: 'در صورت موجود بودن، Apple Wallet (.pkpass) پیوست می‌شود. [نمونه — بدون پاس واقعی]',
    },
    regApproval: {
      title: 'ثبت‌نام تأیید شد',
      preheader: 'ثبت‌نام بلیت تأیید شد — سفارش را کامل کنید',
      alert: 'ثبت‌نام بلیت شما تأیید شد. لطفاً سفارش را کامل کنید تا بلیت‌ها محفوظ بمانند.',
      greeting: (fest, deadline) =>
        `خبر خوب! ثبت‌نام بلیت شما برای ${fest} تأیید شد. سفارش را در زیر کامل کنید. باید تا ${deadline} سفارش را کامل کنید؛ در غیر این صورت ثبت‌نام لغو می‌شود.`,
      summarySubtitle: 'خلاصه ثبت‌نام این ارسال در زیر آمده است.',
      completeOrder: 'تکمیل سفارش',
      summaryTitle: '📋 خلاصه ثبت‌نام',
      buyerTitle: '👤 اطلاعات خریدار',
      ticketsTitle: '🎟️ بلیت‌های ثبت‌شده',
      ticketsSubtitle: 'جزئیات هر بلیت در زیر فهرست شده است.',
      eventTitle: '📍 جزئیات رویداد',
      eventSubtitle: 'زمان و مکان برگزاری رویداد.',
      viewMap: 'مشاهده نقشه ←',
      footerTag: 'رویداد بسازید  ·  ایونتی',
      contactUs: 'تماس با ما',
      autoNote: 'این یک اعلان خودکار از ایونتی است.',
      help: 'نیاز به کمک؟ با info@eveenty.com تماس بگیرید',
      copyright: '© ایونتی. تمامی حقوق محفوظ است.',
    },
    support: null,
  },
  /**
   * FR/ES added for Account Activation only (Task 02 remediation).
   * Other templates stay en/ar/fa — do not offer fr/es in their EMAIL_IDS.locales.
   * Strings from pkg/locales/translations/email/{fr,es}.yaml ActivateEmail*.
   */
  fr: {
    lang: 'fr',
    dir: 'ltr',
    logo: 'fr',
    activate: {
      title: 'Activez votre compte Eveenty',
      welcome: 'Bienvenue sur Eveenty !',
      greeting: 'Bonjour',
      body: "Merci d'avoir créé votre compte Eveenty. Pour commencer, veuillez activer votre compte en cliquant sur le bouton ci-dessous.",
      button: 'Activer mon compte',
      footerLead: 'Ce message a été envoyé à',
      footerSuffix: '.',
      copyright: '© Eveenty. Tous droits réservés.',
    },
    donation: null,
    ticketSale: null,
    regApproval: null,
    support: null,
  },
  es: {
    lang: 'es',
    dir: 'ltr',
    logo: 'es',
    activate: {
      title: 'Active su cuenta Eveenty',
      welcome: '¡Bienvenido a Eveenty!',
      greeting: 'Hola',
      body: 'Gracias por crear su cuenta Eveenty. Para comenzar, active su cuenta haciendo clic en el botón a continuación.',
      button: 'Activar mi cuenta',
      footerLead: 'Este mensaje fue enviado a',
      footerSuffix: '.',
      copyright: '© Eveenty. Todos los derechos reservados.',
    },
    donation: null,
    ticketSale: null,
    regApproval: null,
    support: null,
  },
};

export const EMAIL_IDS = [
  {
    id: 'activate_email',
    label: 'Auth / Simple — activate_email',
    master: 'TRANSACTIONAL',
    figma: '4:2',
    locales: ['en', 'fr', 'es', 'ar', 'fa'],
    variants: ['default'],
  },
  {
    id: 'festival_donation',
    label: 'Financial / Receipt — festival_donation',
    master: 'COMMERCE',
    figma: '21:2',
    locales: ['en', 'ar', 'fa'],
    variants: ['donatorUser', 'organizerNotify'],
  },
  {
    id: 'festival_ticket_sale',
    label: 'Ticket / Pass — festival_ticket_sale',
    master: 'COMMERCE',
    figma: '21:53',
    locales: ['en', 'ar', 'fa'],
    variants: ['buyerUser', 'guestUser'],
  },
  {
    id: 'festival_ticket_registration_approval',
    label: 'Workflow / Status — registration_approval',
    master: 'COMMERCE / Ticket-Pass',
    figma: '48:45',
    locales: ['en', 'ar', 'fa'],
    variants: ['user_completeOrder', 'user_noCta'],
  },
  {
    id: 'support',
    label: 'Internal / Operational — support',
    master: 'NOTIFICATION',
    figma: '22:113',
    locales: ['en'],
    variants: ['default', 'longDetails'],
  },
];
